## Scalar operations 

In [1]:
import dask.array as da

In [3]:
my_arr = da.random.randint(10, size=20, chunks=3)
my_arr

dask.array<randint, shape=(20,), dtype=int64, chunksize=(3,), chunktype=numpy.ndarray>

In [4]:
my_arr.compute()

array([7, 6, 8, 3, 8, 9, 1, 3, 0, 5, 1, 8, 3, 1, 9, 4, 4, 6, 8, 4])

In [5]:
my_hundred_arr = my_arr + 100
my_hundred_arr.compute()

array([107, 106, 108, 103, 108, 109, 101, 103, 100, 105, 101, 108, 103,
       101, 109, 104, 104, 106, 108, 104])

In [6]:
(my_arr * (-1)).compute()

array([-7, -6, -8, -3, -8, -9, -1, -3,  0, -5, -1, -8, -3, -1, -9, -4, -4,
       -6, -8, -4])

## Reductions

In [7]:
dask_sum = my_arr.sum()
dask_sum

dask.array<sum-aggregate, shape=(), dtype=int64, chunksize=(), chunktype=numpy.ndarray>

In [8]:
my_arr.compute()

array([7, 6, 8, 3, 8, 9, 1, 3, 0, 5, 1, 8, 3, 1, 9, 4, 4, 6, 8, 4])

In [9]:
dask_sum.compute()

98

In [10]:
my_ones_arr = da.ones((10,10), chunks=2, dtype=int)

In [11]:
my_ones_arr.compute()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
my_ones_arr.mean(axis=0).compute()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
my_custom_array = da.random.randint(10, size=(4,4), chunks=(1,4))

In [14]:
my_custom_array.compute()

array([[5, 6, 0, 5],
       [7, 4, 2, 8],
       [1, 4, 9, 1],
       [1, 5, 3, 9]])

In [15]:
my_custom_array.mean(axis=0).compute()

array([3.5 , 4.75, 3.5 , 5.75])

In [16]:
my_custom_array.mean(axis=1).compute()

array([4.  , 5.25, 3.75, 4.5 ])

## Slicing

In [17]:
my_custom_array[1:3, 2:4]

dask.array<getitem, shape=(2, 2), dtype=int64, chunksize=(1, 2), chunktype=numpy.ndarray>

In [18]:
my_custom_array[1:3, 2:4].compute()

array([[2, 8],
       [9, 1]])

## Broadcasting

In [19]:
my_custom_array.compute()

array([[5, 6, 0, 5],
       [7, 4, 2, 8],
       [1, 4, 9, 1],
       [1, 5, 3, 9]])

In [20]:
my_small_arr = da.ones(4, chunks=2)
my_small_arr.compute()

array([1., 1., 1., 1.])

In [21]:
brd_example1 = da.add(my_custom_array, my_small_arr)

In [22]:

brd_example1.compute()

array([[ 6.,  7.,  1.,  6.],
       [ 8.,  5.,  3.,  9.],
       [ 2.,  5., 10.,  2.],
       [ 2.,  6.,  4., 10.]])

In [23]:
ten_arr = da.full_like(my_small_arr, 10)

In [24]:
ten_arr.compute()

array([10., 10., 10., 10.])

In [25]:
brd_example2 = da.add(my_custom_array, ten_arr)

In [26]:
brd_example2.compute()

array([[15., 16., 10., 15.],
       [17., 14., 12., 18.],
       [11., 14., 19., 11.],
       [11., 15., 13., 19.]])

## Reshaping

In [27]:
my_custom_array.shape

(4, 4)

In [28]:
custom_arr_1d = my_custom_array.reshape(16)

In [29]:
custom_arr_1d

dask.array<reshape, shape=(16,), dtype=int64, chunksize=(4,), chunktype=numpy.ndarray>

In [30]:
custom_arr_1d.compute()

array([5, 6, 0, 5, 7, 4, 2, 8, 1, 4, 9, 1, 1, 5, 3, 9])

# Stacking

In [31]:
stacked_arr = da.stack([brd_example1, brd_example2])

In [32]:
stacked_arr

dask.array<stack, shape=(2, 4, 4), dtype=float64, chunksize=(1, 1, 2), chunktype=numpy.ndarray>

In [34]:
stacked_arr.compute()

array([[[ 6.,  7.,  1.,  6.],
        [ 8.,  5.,  3.,  9.],
        [ 2.,  5., 10.,  2.],
        [ 2.,  6.,  4., 10.]],

       [[15., 16., 10., 15.],
        [17., 14., 12., 18.],
        [11., 14., 19., 11.],
        [11., 15., 13., 19.]]])

In [35]:
another_stacked = da.stack([brd_example1, brd_example2], axis=1)

In [36]:
another_stacked.compute()

array([[[ 6.,  7.,  1.,  6.],
        [15., 16., 10., 15.]],

       [[ 8.,  5.,  3.,  9.],
        [17., 14., 12., 18.]],

       [[ 2.,  5., 10.,  2.],
        [11., 14., 19., 11.]],

       [[ 2.,  6.,  4., 10.],
        [11., 15., 13., 19.]]])

In [37]:
another_stacked2 = da.stack([brd_example1, brd_example2], axis=0)
another_stacked2

dask.array<stack, shape=(2, 4, 4), dtype=float64, chunksize=(1, 1, 2), chunktype=numpy.ndarray>

In [39]:
another_stacked2.compute()

array([[[ 6.,  7.,  1.,  6.],
        [ 8.,  5.,  3.,  9.],
        [ 2.,  5., 10.,  2.],
        [ 2.,  6.,  4., 10.]],

       [[15., 16., 10., 15.],
        [17., 14., 12., 18.],
        [11., 14., 19., 11.],
        [11., 15., 13., 19.]]])

# Concatenate

In [40]:
concate_arr = da.concatenate([brd_example1, brd_example2])

In [41]:
concate_arr.compute()

array([[ 6.,  7.,  1.,  6.],
       [ 8.,  5.,  3.,  9.],
       [ 2.,  5., 10.,  2.],
       [ 2.,  6.,  4., 10.],
       [15., 16., 10., 15.],
       [17., 14., 12., 18.],
       [11., 14., 19., 11.],
       [11., 15., 13., 19.]])

In [42]:
another_concate_arr = da.concatenate([brd_example1, brd_example2],axis=1)

In [43]:
another_concate_arr.compute()

array([[ 6.,  7.,  1.,  6., 15., 16., 10., 15.],
       [ 8.,  5.,  3.,  9., 17., 14., 12., 18.],
       [ 2.,  5., 10.,  2., 11., 14., 19., 11.],
       [ 2.,  6.,  4., 10., 11., 15., 13., 19.]])